apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo-deployment
  labels:
   app: docker-k8s-dem0
spec:
  replicas: 1
  selector:
   matchLabels:
    app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: prabhupalanivel/sampledocker
          ports:
            - containerPort: 8080
